export const plants = [
  {
    id: 0,
    color: "#3f51b5",
    name: "Tomate",
    toDo: [0],
    wissenschaftlicher_name: "Solanum lycopersicum",
    familie: "Solanaceae",
    pflanzentyp: "Einjährig",
    essbar: true,
    physikalische_merkmale: {
      höhe_cm: 100,
      breite_cm: 50,
      blattbeschreibung:
        "Zusammengesetzte, gefiederte Blätter mit behaarter Oberfläche.",
      blumenbeschreibung: "Kleine, gelbe Blüten in Büscheln.",
      fruchtbeschreibung: "Rot, rund und saftig.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne",
      bodentyp: "Lehmig",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "18-30",
      winterhärtezonen: [10, 11],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Samen"],
      pflanzsaison: "Frühling",
      düngung: "Ausgewogener Dünger alle 2 Wochen",
      schädlinge_und_krankheiten: ["Blattläuse", "Tomatenhornwürmer"],
      schnittanforderungen:
        "Seitentriebe entfernen, um Fruchtwachstum zu fördern",
    },
    nutzung: {
      kulinarische_nutzung: ["Salate", "Soßen", "Suppen"],
      medizinische_nutzung: ["Reich an Vitaminen A und C sowie Lycopin"],
      weitere_nutzung: ["Zierpflanze in Gärten"],
    },
  },
  {
    id: 1,
    color: "#f44336",
    name: "Karotte",
    toDo: [1],
    wissenschaftlicher_name: "Daucus carota subsp. sativus",
    familie: "Apiaceae",
    pflanzentyp: "Zweijährig",
    essbar: true,
    physikalische_merkmale: {
      höhe_cm: 30,
      breite_cm: 15,
      blattbeschreibung: "Gefiederte, grüne Blätter.",
      blumenbeschreibung: "Weiße Blüten in Dolden.",
      fruchtbeschreibung: "Lange, orangefarbene Wurzel.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne bis Halbschatten",
      bodentyp: "Sandig, gut durchlässig",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "10-24",
      winterhärtezonen: [3, 10],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Samen"],
      pflanzsaison: "Frühling oder Herbst",
      düngung: "Kompost vor der Pflanzung einarbeiten",
      schädlinge_und_krankheiten: ["Karottenfliegen", "Nematoden"],
      schnittanforderungen: "Blätter bei Bedarf ausdünnen",
    },
    nutzung: {
      kulinarische_nutzung: ["Rohkost", "Suppen", "Eintöpfe"],
      medizinische_nutzung: ["Reich an Beta-Carotin, gut für die Augen"],
      weitere_nutzung: ["Futterpflanze für Kaninchen"],
    },
  },
  {
    id: 2,
    color: "#ff9800",
    name: "Rose",
    toDo: [0, 2],
    wissenschaftlicher_name: "Rosa",
    familie: "Rosaceae",
    pflanzentyp: "Mehrjährig",
    essbar: false,
    physikalische_merkmale: {
      höhe_cm: 150,
      breite_cm: 100,
      blattbeschreibung: "Zusammengesetzte Blätter mit gezackten Rändern.",
      blumenbeschreibung: "Große, duftende Blüten in verschiedenen Farben.",
      fruchtbeschreibung: "Klein, rot und rund (Hagebutten).",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne bis Halbschatten",
      bodentyp: "Lehmig, gut durchlässig",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "10-25",
      winterhärtezonen: [4, 5, 6, 7, 8, 9],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Stecklinge", "Teilung"],
      pflanzsaison: "Frühling oder Herbst",
      düngung:
        "Rosen-spezifischer Dünger jeden Monat während der Wachstumsperiode",
      schädlinge_und_krankheiten: ["Blattläuse", "Schwarzfleckenkrankheit"],
      schnittanforderungen: "Im späten Winter bis frühen Frühling schneiden",
    },
    nutzung: {
      kulinarische_nutzung: [],
      medizinische_nutzung: ["Hagebutten sind reich an Vitamin C"],
      weitere_nutzung: ["Zierpflanze in Gärten und Blumengestecken"],
    },
  },
  {
    id: 3,
    color: "#4caf50",
    name: "Erdbeere",
    toDo: [1],
    wissenschaftlicher_name: "Fragaria × ananassa",
    familie: "Rosaceae",
    pflanzentyp: "Mehrjährig",
    essbar: true,
    physikalische_merkmale: {
      höhe_cm: 20,
      breite_cm: 30,
      blattbeschreibung: "Gefiederte, gezackte Blätter.",
      blumenbeschreibung: "Weiße Blüten mit gelbem Zentrum.",
      fruchtbeschreibung: "Rote, saftige Beeren mit Samen auf der Oberfläche.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne",
      bodentyp: "Lehmig, gut durchlässig",
      wasserbedarf: "Hoch",
      temperaturbereich_C: "15-25",
      winterhärtezonen: [5, 8],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Ausläufer", "Samen"],
      pflanzsaison: "Frühling oder Herbst",
      düngung: "Organischer Dünger im Frühling",
      schädlinge_und_krankheiten: ["Erdbeermilben", "Grauschimmel"],
      schnittanforderungen:
        "Ausläufer entfernen, um Energie für Fruchtproduktion zu sparen",
    },
    nutzung: {
      kulinarische_nutzung: ["Desserts, Marmeladen, Smoothies"],
      medizinische_nutzung: ["Reich an Vitamin C, Antioxidantien"],
      weitere_nutzung: ["Bodenbedeckung in Gärten"],
    },
  },
  {
    id: 4,
    color: "#ffc107",
    name: "Basilikum",
    toDo: [0, 2],
    wissenschaftlicher_name: "Ocimum basilicum",
    familie: "Lamiaceae",
    pflanzentyp: "Einjährig",
    essbar: true,
    physikalische_merkmale: {
      höhe_cm: 60,
      breite_cm: 30,
      blattbeschreibung: "Ovale, grüne Blätter mit glattem Rand.",
      blumenbeschreibung: "Weiße oder violette Blüten in Ähren.",
      fruchtbeschreibung: "Kleine, schwarze Samen.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne",
      bodentyp: "Gut durchlässiger, nährstoffreicher Boden",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "18-30",
      winterhärtezonen: [10, 11],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Samen", "Stecklinge"],
      pflanzsaison: "Frühling",
      düngung: "Leicht gedüngter Boden alle 4 Wochen",
      schädlinge_und_krankheiten: ["Blattläuse", "Mehltau"],
      schnittanforderungen:
        "Regelmäßig ernten, um buschiges Wachstum zu fördern",
    },
    nutzung: {
      kulinarische_nutzung: ["Pesto, Salate, Pasta"],
      medizinische_nutzung: [
        "Antibakterielle Eigenschaften, Verdauungsfördernd",
      ],
      weitere_nutzung: ["Aromatherapie, Zierpflanze"],
    },
  },
  {
    id: 5,
    color: "#2196f3",
    name: "Paprika",
    toDo: [1, 2],
    wissenschaftlicher_name: "Capsicum annuum",
    familie: "Solanaceae",
    pflanzentyp: "Einjährig",
    essbar: true,
    physikalische_merkmale: {
      höhe_cm: 60,
      breite_cm: 50,
      blattbeschreibung: "Einfache, grüne Blätter mit glattem Rand.",
      blumenbeschreibung: "Weiße Blüten, einzeln oder in Gruppen.",
      fruchtbeschreibung: "Verschiedenfarbige, fleischige Schoten.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Volle Sonne",
      bodentyp: "Lehmig, gut durchlässig",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "18-30",
      winterhärtezonen: [9, 11],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Samen"],
      pflanzsaison: "Frühling",
      düngung: "Ausgewogener Dünger alle 3 Wochen",
      schädlinge_und_krankheiten: ["Blattläuse", "Spinnmilben"],
      schnittanforderungen: "Bei Bedarf Stützen verwenden",
    },
    nutzung: {
      kulinarische_nutzung: ["Salate, Salsas, Gefüllte Paprika"],
      medizinische_nutzung: ["Reich an Vitamin C, Antioxidantien"],
      weitere_nutzung: ["Zierpflanze in Gärten"],
    },
  },
  {
    id: 6,
    color: "#e91e63",
    name: "Fingerhut",
    toDo: [2],
    wissenschaftlicher_name: "Digitalis purpurea",
    familie: "Plantaginaceae",
    pflanzentyp: "Zweijährig",
    essbar: false,
    physikalische_merkmale: {
      höhe_cm: 150,
      breite_cm: 50,
      blattbeschreibung: "Große, lanzenförmige, grüne Blätter.",
      blumenbeschreibung:
        "Röhrenförmige, violette bis rosafarbene Blüten in hohen Trauben.",
      fruchtbeschreibung: "Kleine, trockene Kapseln mit zahlreichen Samen.",
    },
    wachstumsbedingungen: {
      sonnenlicht: "Halbschatten bis volle Sonne",
      bodentyp: "Gut durchlässiger, humusreicher Boden",
      wasserbedarf: "Mittel",
      temperaturbereich_C: "10-20",
      winterhärtezonen: [4, 8],
    },
    pflanzung_und_pflege: {
      vermehrungsmethoden: ["Samen"],
      pflanzsaison: "Frühling oder Herbst",
      düngung: "Kompost oder organischer Dünger im Frühjahr",
      schädlinge_und_krankheiten: ["Blattläuse", "Mehltau"],
      schnittanforderungen:
        "Nach der Blüte zurückschneiden, um neues Wachstum zu fördern",
    },
    nutzung: {
      kulinarische_nutzung: [],
      medizinische_nutzung: [
        "Enthält Herzglykoside, die in der Medizin verwendet werden",
      ],
      weitere_nutzung: ["Zierpflanze in Gärten, Bienenweide"],
    },
  },
];
